### ISSUE TITLE
Resolving APIC-EM crashes

### ISSUE THREAD

**Issue by securenetwrk** [CiscoDevNet/devnet-express-dna-issues#15] opened 2017-04-12 21:37 UTC
Several pods typically have APIC-EM crash during the event. To fix it, you can VPN in to the pod, SSH to 198.18.129.100, log in as user grapevine, password C1sco12345, and run reset_grapevine. Be sure to answer NO to all questions and after an hour or two it should be back online. I did not log the exact time to run it.

**Comment by austinMarcos** [comment] 2017-04-14 16:52
Yawming will investigate with Eddie.

**Comment by austinMarcos** [comment] 2017-05-19 15:33
@yawming reports that issue is difficult to re-produce. This team does not have an immediate fix to this issue.  @cmlccie asks: "Can we come up with a process that mitigates the symptoms. Currently the SEs have to spin up a new pod for the student."

**Comment by ecorban** [comment] 2017-05-19 18:56
The fastest method to resolve this issue is to login via ssh to apic-em and reset_grapevine. This takes approx.. 45 to resolve. This was documented already
By other users.



[logo_Grey]



Eddie Corban
TECHNICAL LEADER.ENGINEERING
ecorban@cisco.com<mailto:ecorban@cisco.com>
Tel: +353 91 38 4623

Cisco Systems, Inc.
Oranmore Business Park Oranmore
GALWAY

Ireland
cisco.com


[http://www.cisco.com/assets/swa/img/thinkbeforeyouprint.gif]Think before you print.

This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message.
Please click here<http://www.cisco.com/web/about/doing_business/legal/cri/index.html> for Company Registration Information.

**Comment by yawming** [comment] 2017-05-19 19:12
45 min id too long. I think quicker way is to have a few reserved pods and have an easy and quick way to assign new pod to user.

**Comment by cmlccie** [comment] 2017-05-19 19:19
@yawming I think @ecorban meant 45s.  😏  If that is the case, and the best we can do at the moment, perhaps the initial resolution should be to note this workaround / resolution in an appropriate place.

**Comment by yawming** [comment] 2017-05-19 19:22
I don’t think reset_grapevine only take 45s. It will re-grow all apic-em services.

**Comment by yawming** [comment] 2017-06-01 17:01
Proposed solution:
Have a few reserved pods ready. Patrick Riel will create a automation app so whoever needs to assign a new pod to the user just need to input simple user's information (like email) then new pod will be ready for that user in seconds, new pod's login info will be sent via provided email.

**Comment by austinMarcos** [comment] 2017-06-02 15:21
**Status**
@Iftach agreed that it's worth having Patrick create the script for quick re-assignment of a pod.

@Iftach suggests investing more effort into debugging to do more root-cause analysis (collect log data for example to identify root cause).  Yawming would need to consult with @Eddie APIC-EM teams to figure out how to do further analysis, and find out whether the next version of APIC-EM will solve this.

**Comment by austinMarcos** [comment] 2017-06-15 15:53
Based on feedback from Pedro:  It appears that when the pod golden image is created that if APIC-EM is not shutdown properly it can create an unstable state when it is next started. It is possible that the existing image that was being used for v2 had not been properly shut down. The new pod image for v2.2 addresses this.

**Comment by armartirosyan** [comment] 2017-07-11 15:45
The APIC-EM was properly shutdown for 2.1 but users are still reporting issues with it.

**Comment by austinMarcos** [comment] 2017-07-20 16:12
This issue was not resolved with the rollout of pod v2.1. 

- We still need to solve the problem. Take a look at whether to update APIC-EM, or re-assign the pod.
- Immediately:  Need to publish this as a known issue.

**Comment by austinMarcos** [comment] 2017-08-02 17:14
This issue was published as a **known issue** in the box folder where event hosts obtain their slide decks and release notes:
https://cisco.app.box.com/files/0/f/22509384263/v2.1-DNA-slides_and_release_notes

**Closed** 2020-03-31 16:00 UTC
Labels: Priority-2, STATE: IN PROGRESS, Severity-2, bug
