### ISSUE TITLE
Using the CentOS workstation in dcloud/Devnet Express, pip install -r requirements.txt fails !

### ISSUE THREAD

**Issue by makarthi** [CiscoDevNet/devnet-express-dna-issues#101] opened 2020-04-09 20:20 UTC
HI Team,

Pip install -r requirements.txt is failing on a fresh CentOS from dcloud/Devnet.

It is failing on CiscoSPARKAPI... Can somebody look asap.

Mak

**Comment by kiskander** [comment] 2020-04-09 20:26
Hey Mak,
what's the error you are getting?

**Comment by makarthi** [comment] 2020-04-09 20:45
HI Kiskander
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I hashed out CiscoSPARKAPI, but problem remains with ncclient. Looks like a version issue?

**Comment by makarthi** [comment] 2020-04-09 20:47
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting ncclient==0.6.0
  Using cached ncclient-0.6.0.tar.gz (69 kB)
    ERROR: Command errored out with exit status 1:
     command: /bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-S2NEN1/ncclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-S2NEN1/ncclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-S2NEN1/ncclient/pip-egg-info
         cwd: /tmp/pip-install-S2NEN1/ncclient/
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-S2NEN1/ncclient/setup.py", line 59, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2334, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'check_specifier'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by annegentle** [comment] 2020-04-09 20:50
Hi, I believe `ncclient` has several requirements prior to the `requirements.txt` step.

What system are you trying this on? 

From https://pypi.org/project/ncclient/, these are the additional requirements:

Python 2.7 or Python 3.4+
setuptools 0.6+
Paramiko 1.7+
lxml 3.3.0+
libxml2
libxslt

**Comment by makarthi** [comment] 2020-04-09 20:57
[developer@centos dnav3-code]$ more requirements.txt
# ciscosparkapi==0.9.2
ncclient==0.6.0
netmiko==1.4.2
pyang==1.7.4
requests==2.20.0
urllib3==1.24.2
xmltodict==0.11.0
ansible==2.5.4

**Comment by makarthi** [comment] 2020-04-09 20:58
is my requirements.txt  wrong then?

**Comment by makarthi** [comment] 2020-04-09 20:59
I am just using the CentOS that comes with default on the dcloud devnet exptress (DNAv3) pods. Prepping for a Devnet express event and trying to commands in sequence as per the learning module.

**Comment by annegentle** [comment] 2020-04-09 21:12
I'm glad you're testing. 

The "Requirements" for `ncclient` are typically installed using yum- (or apt-) based package managers as I understand it. So in the case of the dcloud CentOS installation, you should be able to follow the instructions as written.  Can you find out the underlying CentOS packages with `yum list installed`?

**Comment by makarthi** [comment] 2020-04-09 21:18
Thanks Anne, Thanks Kiskander. Let me try with a fresh dcloud instance. Maybe I have a dud.

**Comment by denapom11** [comment] 2020-04-09 22:09
Hey Mak,

Is this error occuring inside a python virtual environment setup for python 3.x?  Error looks like the problem is happening on install of 2.7 which none of the code for DNA is written for.  If not can you try?

**Comment by makarthi** [comment] 2020-04-09 22:13
ah okay, Let me try that. Thanks Denapom11
Possible I might have deactivated the venv while trying this.

**Comment by makarthi** [comment] 2020-04-09 22:49
It works guys... I did a new dcloud instance. And this time I ensure I am in an activated virtual environment. Suspect it was my mistake before, may not have been in an activated virtual instance.

Thanks Anne, Kiskander, Matthew DeNapoli !

**Comment by kiskander** [comment] 2020-04-09 22:55
curious, what happens if you do pip3 install -r requirements.txt ?

**Comment by makarthi** [comment] 2020-04-09 23:09
pip3 is not there... getting an error like this (Manual typing below)

bash:pip3: command not found

**Comment by annegentle** [comment] 2021-01-15 14:42
Closing, since once the instructions are followed to the letter it works -- though it is good to know that `pip3` is not the installation on the dcloud instance, so thanks for testing!

**Closed as completed by annegentle** 2021-01-15 14:42 UTC
